name: Sync and Update

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora
  workflow_dispatch: # Permite a execução manual através da UI do GitHub

jobs:
  sync_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from secondary project
        uses: actions/checkout@v2
        with:
          repository: pedroslopez/whatsapp-web.js
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      

      - name: Fetch Upstream Changes
        run: |
          git remote add upstream https://github.com/pedroslopez/whatsapp-web.js
          git fetch upstream

      - name: Configure Git User
        run: |
          git config user.email "andytargino@outlook.com"
          git config user.name "AndyTargino"

      - name: Reset and Update from Upstream
        run: |
          git checkout main
          git reset --hard upstream/main
          git checkout HEAD README.md        # Restores the README.md
          git checkout HEAD .github/         # Restores the .github folder
          git checkout HEAD .eslintrc.json   # Restores the .eslintrc.json

      - name: Replace puppeteer dependency with puppeteer-in-electron
        run: |
          jq '.dependencies["puppeteer-in-electron"] = "^3.0.5"' package.json > temp.json && mv temp.json package.json
          jq 'del(.dependencies["puppeteer"])' package.json > temp2.json && mv temp2.json package.json

      - name: Make Code Substitutions in Client.js
        run: |
          FILE_PATH="src/Client.js"
          sed -i 's|const puppeteer = require('"'"'puppeteer'"'"');|const pie = require('"'"'puppeteer-in-electron'"'"');|g' $FILE_PATH
          sed -i 's|constructor(options = {})|constructor(puppeteerBrowser, browserWindow, options = {})|' $FILE_PATH
          sed -i 's|this.pupBrowser = null;|this.pupBrowser = puppeteerBrowser;\n        this.browserWindow = browserWindow;|' $FILE_PATH
          sed -i '/let \[browser, page\] = \[null, null\];/,/await page.authenticate(this.options.proxyAuthentication);/c\        const page = await pie.getPage(this.pupBrowser, this.browserWindow);\n        page.setUserAgent(this.options.userAgent);' $FILE_PATH
          sed -i '/this.pupBrowser = browser;/d' $FILE_PATH

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Synchronized with upstream and applied custom changes" || echo "No changes to commit"
          git remote set-url origin https://${{ secrets.RELEASE_GITHUB_TOKEN }}@github.com/AndyTargino/wwebjs-electron.git
          git push --force
