name: Sync and Update

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora
  workflow_dispatch: # Permite a execução manual através da UI do GitHub

jobs:
  sync_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Obter a última versão da release do projeto base
        id: latest_version
        run: |
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/pedroslopez/whatsapp-web.js/releases/latest" | jq -r .tag_name)
          echo "::set-output name=version::$LATEST_VERSION"
          echo "Última versão da release obtida: $LATEST_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout da branch main
        uses: actions/checkout@v2
        with:
          repository: AndyTargino/wwebjs-electron
          ref: main
          fetch-depth: 0

      - name: Criar e fazer checkout para uma nova branch
        run: |
          BRANCH_NAME=update-$(date +'%Y%m%d%H%M%S')
          git checkout -b $BRANCH_NAME

      - name: Aplicar modificações
        run: |
          # Restaurar arquivos específicos do seu repositório
          git checkout 61e146ef67126ba320f7d97aae2d6189e066fd9c -- README.md .github/ .eslintrc.json
          # ... (resto do código com suas modificações)

      - name: Fazer checkout para main e merge da nova branch
        run: |
          git checkout main
          git merge --no-ff --allow-unrelated-histories -m "Merging updates" $BRANCH_NAME

      - name: Commit e Push
        run: |
          git config user.email "andytargino@outlook.com"
          git config user.name "AndyTargino"
          git add .
          git commit -m "Synchronized with upstream and applied custom changes" || echo "No changes to commit"
          git remote set-url origin https://${{ secrets.RELEASE_GITHUB_TOKEN }}@github.com/AndyTargino/wwebjs-electron.git
          git push --force
          echo "Mudanças commitadas e enviadas."
