name: Atualizar a partir de whatsapp-web.js

on:
  schedule:
    - cron: '0 0 * * *' # isso irá rodar todos os dias às 00:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wwebjs-electron
        uses: actions/checkout@v2
        with:
          repository: AndyTargino/wwebjs-electron

      - name: Obter a versão mais recente de whatsapp-web.js
        id: latest_version
        run: |
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/pedroslopez/whatsapp-web.js/releases/latest" | jq -r .tag_name)
          echo "Versão mais recente é $LATEST_VERSION"
          echo ::set-output name=version::$LATEST_VERSION

      - name: Checkout a versão mais recente de whatsapp-web.js
        uses: actions/checkout@v2
        with:
          repository: pedroslopez/whatsapp-web.js
          ref: ${{ steps.latest_version.outputs.version }}
          path: ./whatsapp-web.js

      - name: Copiar arquivos e fazer alterações
        run: |
          # Copiar arquivos
          cp -r whatsapp-web.js/* ./
          
          # Mantendo arquivos específicos
          git checkout HEAD -- package.json .eslintrc.json README.md .github/
          
          # Modificar src/Client.js
          sed -i 's|const puppeteer = require('\''puppeteer'\'');|const pie = require('\''puppeteer-in-electron'\'');|g' src/Client.js
          sed -i 's|constructor(options = {}) {|constructor(puppeteerBrowser, browserWindow, options = {}) {|g' src/Client.js
          sed -i 's|this.pupBrowser = null;|this.pupBrowser = puppeteerBrowser;\nthis.browserWindow = browserWindow;|g' src/Client.js
          sed -i 's|let \[browser, page\] = \[null, null\];\n.*browser.pages\)\[0\];|const page = await pie.getPage(this.pupBrowser, this.browserWindow);\n        page.setUserAgent(this.options.userAgent);|gs' src/Client.js
          sed -i '/this.pupBrowser = browser;/d' src/Client.js

      - name: Criar e subir a nova branch
        run: |
          git checkout -b ${{ steps.latest_version.outputs.version }}
          git add .
          git commit -m "Atualizado a partir de whatsapp-web.js ${steps.latest_version.outputs.version}"
          git push origin ${{ steps.latest_version.outputs.version }}
